#define RAGETBOT_TEXT  "Ragebot"
#define LIGETBOT_TEXT  "Legitbot"

#define COLORS_TEXT  "Colors"
#define CONFIG_TEXT  "Config"
#define ESP_TEXT  "ESP"
#define SETTINGS_TEXT  "Settings"
#define SKINS_TEXT  "Skins"
#define SKINS_StatTrak_TEXT  "Skins StatTrak"
#define SKINS_Seed_TEXT  "Skins StatTrak"

#define Sticker_Active_TEXT  "Sticker_Active"
#define Sticker_Slot1_TEXT  "Sticker_Slot1"
#define Sticker_Slot2_TEXT  "Sticker_Slot2"
#define Sticker_Slot3_TEXT  "Sticker_Slot3"
#define Sticker_Slot4_TEXT  "Sticker_Slot4"
#define Sticker_Slot5_TEXT  "Sticker_Slot5"

#define SKINS_Wear_TEXT  "Skins Wear"
#define SKINS_Quality_TEXT  "Skins Quality"

#define MISC_TEXT  "Misc"
#define RADAR_TEXT  "Radar"

#define R_MainSwitch  "MainSwitch"
#define R_Enabled  "Enabled"
#define R_AutoFire  "AutoFire"
#define R_FOV  "FOV"
#define R_TargetSelection  "TargetSelection"
#define R_Silent  "Silent"
#define R_AutoPistol  "AutoPistol"
#define R_KeyPress  "KeyPress"
#define R_EnabledAntiAim  "EnabledAntiAim"
#define R_PreAAs  "PreAAs"
#define R_Pitch  "Pitch"
#define R_YawTrue  "YawTrue"
#define R_YawFake  "YawFake"
#define R_YawTrueAdder  "YawTrueAdder"
#define R_YawFakeAdder  "YawFakeAdder"
#define R_PitchAdder  "PitchAdder"
#define R_AtTarget  "AtTarget"
#define R_Edge  "Edge"
#define R_KnifeAA  "KnifeAA"
#define R_BuilderAAs  "BuilderAAs"
#define R_Jitter  "Jitter"
#define R_FJitter  "FJitter"
#define R_LBYBreaker  "LBYBreaker"
#define R_BuilderReal  "BuilderReal"
#define R_BuilderFake  "BuilderFake"
#define R_BuilderPitch  "BuilderPitch"
#define R_JitterRange  "JitterRange"
#define R_FJitterRange  "FJitterRange"
#define R_FriendlyFire  "FriendlyFire"
#define R_autowall  "autowall"
#define R_Hitbox  "Hitbox"
#define R_Hitscan  "Hitscan"
#define R_NoSpread  "NoSpread"
#define R_AntiRecoil  "AntiRecoil"
#define R_AntiSpread  "AntiSpread"
#define R_AutoStop  "AutoStop"
#define R_AutoCrouch  "AutoCrouch"
#define R_AutoScope  "AutoScope"
#define R_AIFakeLag  "AIFakeLag"
#define R_AIFakeLagAmt  "AIFakeLagAmt"
#define R_FakeLagType "FakeLagType"
#define R_MinimumDamage  "MinimumDamage"
#define R_Hitchance  "Hitchance"
#define R_HitchanceAmount  "HitchanceAmount"
#define R_Resolver  "Resolver"
#define R_FakeLagFix  "FakeLagFix"
#define R_PosAdjust  "PosAdjust"
#define R_playerlist  "playerlist"
#define R_BAIMkey  "BAIMkey"
#define R_bruteAfterX  "bruteAfterX"
#define R_AntiSmac  "AntiSmac"
#define R_HitscanInvis  "HitscanInvis"
#define R_MinimumDamageSniper  "MinimumDamageSniper"
#define R_MinimumDamageRifle  "MinimumDamageRifle"
#define R_MinimumDamagePistol  "MinimumDamagePistol"
#define R_MinimumDamageHeavy  "MinimumDamageHeavy"
#define R_MinimumDamageSmg  "MinimumDamageSmg"
#define R_MinimumDamageRevolver  "MinimumDamageRevolver"
#define R_HitchanceSniper  "HitchanceSniper"
#define R_HitchancePistol  "HitchancePistol"
#define R_HitchanceRifle  "HitchanceRifle"
#define R_HitchanceHeavy  "HitchanceHeavy"
#define R_HitchanceSmgs  "HitchanceSmgs"
#define R_HitchanceRevolver  "HitchanceRevolver"
#define R_Multipoint  "Multipoint"
#define R_Pointscalex  "Pointscalex"
#define R_Pointscaley  "Pointscaley"
#define R_Fakelag "Fakelag"
#define R_FakelagMode "FakelagMode"
#define R_FakeLagAmt "FakeLagAmt"

#define R_AimbotResolver "AimbotResolver"
#define R_Resolver3 "Resolver3"
#define R_LBYCorrection "LBYCorrection"
#define R_LBYCorrection2 "LBYCorrection2"
#define R_RageINFO "RageINFO"
#define R_flipkey "flipkey"

#define L_MainSwitch  "MainSwitch"
#define L_backtrack  "backtrack"
#define L_backtrackTicks  "backtrackTicks"
#define L_backtrackSize "backtrackSize"
#define L_Enabled  "Enabled"
#define L_Resolver  "Resolver"
#define L_AntiAim  "AntiAim"
#define L_ALegitAA  "ALegitAA"
#define L_checksmoke  "checksmoke"
#define L_LAA  "LegitAA"
#define L_AAAngle  "AAAngle"

#define L_PistolKey  "PistolKey"
#define L_Pistolfov  "Pistolfov"
#define L_Pistol_FakeLag  "Pistol_FakeLag"
#define L_Pistol_FakeLag_Mode  "Pistol_FakeLag_Mode"
#define L_Pistol_FakeLag_Value  "Pistol_FakeLag_Value"
#define L_PistolSmooth  "PistolSmooth"
#define L_PistolHitbox  "PistolHitbox"
#define L_pistol_rcs  "pistol_rcs"
#define L_pistol_mode  "pistol_mode"
#define L_pistol_AutoPistol  "AutoPistol"
#define L_pistol_AutoLock "pistol_AutoLock"
#define L_Pistol_Silent "Pistol_Silent"
#define L_pistol_TriggerbotKey  "pistol_TriggerbotKey"
#define L_pistol_Triggerbot_hitchance  "pistol_Triggerbot_hitchance"
#define L_Pistol_Triggerbot_AutoFire  "Pistol_Triggerbot_AutoFire"
#define L_Pistol_Triggerbot  "Pistol_Triggerbot"
#define L_Pistol_Triggerbot_Head  "Pistol_Triggerbot_Head"
#define L_Pistol_Triggerbot_Arms  "Pistol_Triggerbot_Arms"
#define L_Pistol_Triggerbot_Chest  "Pistol_Triggerbot_Chest"
#define L_Pistol_Triggerbot_Stomach  "Pistol_Triggerbot_Stomach"
#define L_Pistol_Triggerbot_Legs  "Pistol_Triggerbot_Legs"

#define L_heavyKey  "heavyKey"
#define L_heavyfov  "heavyfov"
#define L_heavy_FakeLag  "heavy_FakeLag"
#define L_heavy_FakeLag_Mode  "heavy_FakeLag_Mode"
#define L_heavy_FakeLag_Value  "heavy_FakeLag_Value"
#define L_heavySmooth  "heavySmooth"
#define L_heavyHitbox  "heavyHitbox"
#define L_heavy_rcs  "heavy_rcs"
#define L_heavy_mode  "heavy_mode"
#define L_heavy_AutoLock "heavy_AutoLock"
#define L_heavy_Silent "heavy_Silent"
#define L_heavy_TriggerbotKey  "heavy_TriggerbotKey"
#define L_heavy_Triggerbot_hitchance  "heavy_Triggerbot_hitchance"
#define L_heavy_Triggerbot_AutoFire  "heavy_Triggerbot_AutoFire"
#define L_heavy_Triggerbot  "heavy_Triggerbot"
#define L_heavy_Triggerbot_Head  "heavy_Triggerbot_Head"
#define L_heavy_Triggerbot_Arms  "heavy_Triggerbot_Arms"
#define L_heavy_Triggerbot_Chest  "heavy_Triggerbot_Chest"
#define L_heavy_Triggerbot_Stomach  "heavy_Triggerbot_Stomach"
#define L_heavy_Triggerbot_Legs  "heavy_Triggerbot_Legs"

#define L_smgKey  "smgKey"
#define L_smgfov  "smgfov"
#define L_smg_FakeLag  "smg_FakeLag"
#define L_smg_FakeLag_Mode  "smg_FakeLag_Mode"
#define L_smg_FakeLag_Value  "smg_FakeLag_Value"
#define L_smgSmooth  "smgSmooth"
#define L_smgHitbox  "smgHitbox"
#define L_smg_rcs  "smg_rcs"
#define L_smg_mode  "smg_mode"
#define L_smg_AutoLock "smg_AutoLock"
#define L_smg_Silent "smg_Silent"
#define L_smg_TriggerbotKey  "smg_TriggerbotKey"
#define L_smg_Triggerbot_hitchance  "smg_Triggerbot_hitchance"
#define L_smg_Triggerbot_AutoFire  "smg_Triggerbot_AutoFire"
#define L_smg_Triggerbot  "smg_Triggerbot"
#define L_smg_Triggerbot_Head  "smg_Triggerbot_Head"
#define L_smg_Triggerbot_Arms  "smg_Triggerbot_Arms"
#define L_smg_Triggerbot_Chest  "smg_Triggerbot_Chest"
#define L_smg_Triggerbot_Stomach  "smg_Triggerbot_Stomach"
#define L_smg_Triggerbot_Legs  "smg_Triggerbot_Legs"

#define L_MainKey  "MainKey"
#define L_MainSmooth  "MainSmooth"
#define L_MainHitbox  "MainHitbox"
#define L_Mainfov  "Mainfov"
#define L_main_FakeLag  "main_FakeLag"
#define L_main_FakeLag_Mode  "main_FakeLag_Mode"
#define L_main_FakeLag_Value  "main_FakeLag_Value"
#define L_main_rcs  "main_rcs"
#define L_main_mode  "main_mode"
#define L_main_AutoLock "main_AutoLock"
#define L_main_Silent "main_Silent"
#define L_main_TriggerbotKey  "main_TriggerbotKey"
#define L_main_Triggerbot_hitchance  "main_Triggerbot_hitchance"
#define L_main_Triggerbot_AutoFire  "main_Triggerbot_AutoFire"
#define L_main_Triggerbot  "main_Triggerbot"
#define L_main_Triggerbot_Head  "main_Triggerbot_Head"
#define L_main_Triggerbot_Arms  "main_Triggerbot_Arms"
#define L_main_Triggerbot_Chest  "main_Triggerbot_Chest"
#define L_main_Triggerbot_Stomach  "main_Triggerbot_Stomach"
#define L_main_Triggerbot_Legs  "main_Triggerbot_Legs"

#define L_SniperKey "SniperKey"
#define L_Sniperfov "Sniperfov"
#define L_sniper_FakeLag  "sniper_FakeLag"
#define L_sniper_FakeLag_Mode  "sniper_FakeLag_Mode"
#define L_sniper_FakeLag_Value  "sniper_FakeLag_Value"
#define L_SniperSmooth "SniperSmooth"
#define L_SniperHitbox "SniperHitbox"
#define L_sniper_rcs "sniper_rcs"
#define L_sniper_mode "sniper_mode"
#define L_sniper_fastzoom  "fastzoom"
#define L_sniper_fastzoomswitch  "fastzoomswitch"
#define L_sniper_AutoLock "sniper_AutoLock"
#define L_sniper_Silent "sniper_Silent"
#define L_sniper_TriggerbotKey  "sniper_TriggerbotKey"
#define L_sniper_Triggerbot  "sniper_Triggerbot"
#define L_sniper_Triggerbot_hitchance  "sniper_Triggerbot_hitchance"
#define L_sniper_Triggerbot_AutoFire  "sniper_Triggerbot_AutoFire"
#define L_sniper_Triggerbot_Head  "sniper_Triggerbot_Head"
#define L_sniper_Triggerbot_Arms  "sniper_Triggerbot_Arms"
#define L_sniper_Triggerbot_Chest  "sniper_Triggerbot_Chest"
#define L_sniper_Triggerbot_Stomach  "sniper_Triggerbot_Stomach"
#define L_sniper_Triggerbot_Legs  "sniper_Triggerbot_Legs"

#define L_RevolverKey "RevolverKey"
#define L_Revolverfov "Revolverfov"
#define L_Revolver_FakeLag  "Revolver_FakeLag"
#define L_Revolver_FakeLag_Mode  "Revolver_FakeLag_Mode"
#define L_Revolver_FakeLag_Value  "Revolver_FakeLag_Value"
#define L_RevolverSmooth "RevolverSmooth"
#define L_RevolverHitbox "RevolverHitbox"
#define L_Revolver_rcs "Revolver_rcs"
#define L_Revolver_mode "Revolver_mode"
#define L_Revolver_AutoLock "Revolver_AutoLock"
#define L_Revolver_Silent "Revolver_Silent"
#define L_Revolver_TriggerbotKey  "Revolver_TriggerbotKey"
#define L_Revolver_Triggerbot  "Revolver_Triggerbot"
#define L_Revolver_Triggerbot_hitchance  "Revolver_Triggerbot_hitchance"
#define L_Revolver_Triggerbot_AutoFire  "Revolver_Triggerbot_AutoFire"
#define L_Revolver_Triggerbot_Head  "Revolver_Triggerbot_Head"
#define L_Revolver_Triggerbot_Arms  "Revolver_Triggerbot_Arms"
#define L_Revolver_Triggerbot_Chest  "Revolver_Triggerbot_Chest"
#define L_Revolver_Triggerbot_Stomach  "Revolver_Triggerbot_Stomach"
#define L_Revolver_Triggerbot_Legs  "Revolver_Triggerbot_Legs"

#define E_Enabled "Enabled"
#define E_Box "Box"
#define E_Name "Name"
#define E_Skeleton "Skeleton"
#define E_OffscreenIndicator "OffscreenIndicator"
#define E_GrenadeBox "GrenadeBox"
#define E_Chicken "Chicken"
#define E_DroppedGuns "DroppedGuns"
#define E_C4World "C4World"
#define E_Weapon "Weapon"
#define E_skeletonopts "skeletonopts"
#define E_Grenades "Grenades"
#define E_OffscreenIndicatorSize "OffscreenIndicatorSize"
#define E_IsHasDefuser "IsHasDefuser"
#define E_Scoped "Scoped"
#define E_BombCarrier "BombCarrier"
#define E_Flashed "Flashed"
#define E_Distance "Distance"
#define E_Money "Money"
#define E_IsReloading "IsReloading"
#define E_Callout "Callout"
#define E_Hitbox "Hitbox"
#define E_HitboxDuration "HitboxDuration"
#define E_DroppedGunsType "DroppedGunsType"
#define E_Armor2 "Armor2"

#define E_Info "Info"
#define E_AimSpot "AimSpot"
#define E_DLight "DLight"
#define E_glowplayer "glowplayer"
#define E_RecoilCrosshair "RecoilCrosshair"
#define E_Weapons "Weapons"
#define E_WeaponsWorld "WeaponsWorld"
#define E_LBYIndicator "LBYIndicator"
#define E_Chams "Chams "
#define E_Teamchams "Teamchams"
#define E_XQZ "XQZ"
#define E_weaponglow "weaponglow"
#define E_teamglow "teamglow"
#define E_bombglow "bombglow"
#define E_BoxType "BoxType"
#define E_TeamESP "TeamESP"
#define E_angleLines "angleLines"
#define E_DrawAwall "DrawAwall"
#define E_AimLine "AimLine"
#define E_health "health"
#define E_barrel "barrel"
#define E_droppedchams "weaponsdroppedchams"
#define E_barrelL "barrelL"
#define E_Playermatierial "Playermatierial"
#define E_Weaponsdroppedmatierial "Weaponsdroppedmatierial"
#define E_angleLines "angleLines"
#define E_esp_Visible "esp_Visible"
#define E_esp_corpses "Deads Players"
#define E_esp_fillbox "fillBox"
#define E_esp_armor "armor"
#define E_esp_bulletshow "bulletshow"
#define E_esp_flTracersDuration "flTracersDuration"
#define E_esp_flTracersWidth "flTracersWidth"
#define E_esp_healthtype "healthtype"
#define E_esp_chamsHp "chamsHp"
#define E_esp_fill_amount "fillbox_amount"
#define E_chams_fakeangle "chams_fakeangle"
#define E_AWallCrosshair "AWallCrosshair"
#define E_SniperCrosshair "SniperCrosshair"
#define E_SniperCrosshairType "SniperCrosshairType"
#define E_CrosshairOn "CrosshairOn"
#define E_CrosshairSpread "CrosshairSpread"
#define E_CrosshairType "CrosshairType"
#define E_CrosshairStyle "CrosshairStyle"
#define E_CrosshairRainbow "CrosshairRainbow"



#define M_FOVChanger "FOVChanger"
#define M_viewmodelChanger "viewmodelChanger"
#define M_NoFlashr "NoFlash"
#define M_NoSmoke "NoSmoke"
#define M_NoFlash "NoFlash"
#define M_Hands "Hands"
#define M_ThirdPerson "ThirdPerson"
#define M_Time "Time"
#define M_noscopeborder "noscopeborder"
#define M_GrenadePrediction "GrenadePrediction"
#define M_handcham "handcham"
#define M_Hitmarker "Hitmarker"
#define M_HitmarkerSound "HitmarkerSound"
#define M_silentstealer "silentstealer"
#define M_hidename "hidename"
#define M_Bhop "Bhop"
#define M_AutoStrafe "AutoStrafe"
#define M_Ranks "Ranks"
#define M_NameSpammer "NameSpammer"
#define M_NameChangerFix "NameChangerFix"
#define M_NoName "NoName"
#define M_ChatSpamMode "ChatSpamMode"
#define M_ClantagChanger "ClantagChanger"
#define M_ClanTagSpeed "ClanTagSpeed"
#define M_syncclantag "syncclantag"
#define M_SpecList "SpecList"
#define M_namespam "namespam"
#define M_spammer "spammer"
#define M_isRecording "isRecording"
#define M_isReplaying "isReplaying"
#define M_RecordPath "RecordPath"
#define M_AutoAccept "AutoAccept"
#define M_animatedclantag "animatedclantag"
#define M_namespeed "namespeed"
#define M_Crosshair "Crosshair"
#define M_Crosshair2 "Crosshair2"
#define M_SkyShit "SkyShit"
#define M_NoSky "NoSky"
#define M_boostbhop "boostbhop"
#define M_AirlockKey "AirlockKey"
#define M_ASUSWALL "ASUSWALL"
#define M_handmat "handmat"
#define M_weaponhandmat "weaponhandmat"
#define M_WeaponsLog "WeaponsLog"
#define M_DMGLog "DMGLog"
#define M_TPKey "TPKey"
#define M_misc_SkyName "misc_SkyName"
#define M_Snow "Snow"
#define M_postprocess "postprocess"
#define M_FakeWalk  "FakeWalk"
#define M_FakeWalkkey  "FakeWalkkey"
#define M_RCS "RCS"
#define M_RCS_Distortion "RCS_Distortion"
#define M_NRCS "NRCS"
#define M_RCS_NDistortion "RCS_NDistortion"
#define M_RecoilCrosshair "RecoilCrosshair"
#define M_bFreeCam "bFreeCam"
#define M_iFreeCamKey "iFreeCamKey"
#define M_flFreeCamSpeed "flFreeCamSpeed"
#define M_flFreeCamSpeed "flFreeCamSpeed"
#define M_bBlockbot "Blockbot"
#define M_iBlockbotKey "iBlockbotKey"
#define M_customodelsct "customodelsct"
#define M_customodelst "customodelst"
#define M_misc_inventory "inventory"

#define M_Knf_Active "Knf_Active"
#define M_knf_Team "knf_Team"
#define M_knf_Attack "knf_Attack"
#define M_knf_DistAttack "knf_DistAttack"
#define M_knf_DistAttack2 "knf_DistAttack2"
#define M_moonwalk "moonwalk"
#define M_moonwalkkey "moonwalkkey"



#define M_WeaponsHandMat "WeaponsHandMat"
#define M_HandMat "HandMat"
#define M_Hitsound "Hitsound"

#define R_radaringame "radaringame"
#define R_radarwindow "radarwindow"
#define R_radrsize "radrsize"

#define R_radralpha "radralpha"

#define R_radrzoom "radrzoom"
#define R_rad_Vis "rad_Vis"
#define R_rad_Range "rad_Range"


#define S_Enabled "Enabled"
#define S_knifemodel "knifemodel"
#define S_glove "glove"
#define S_gloveskin "gloveskin"
#define CW_currentWeapon "currentWeapon"
#define S_EnabledSticker "Enable_Sticker"


#define	C_champlayeralpha "champlayeralpha"
#define	C_chamhandalpha "chamhandalpha"
#define	C_weaponhandalpha "weaponhandalpha"
#define	C_weaponglowalpha "weaponglowalpha"
#define	C_playerglowalpha "playerglowalpha"
#define	C_bombglowalpha "bombglowalpha"
#define	C_weaponsworldalph "weaponsworldalph"
#define	C_weponchamsalph "weponchamsalph"
#define	C_esp_Ambient "esp_Ambient"
#define	C_backtrack "backtrack"
#define	C_color_sniper "color_sniper"
#define	C_GrenadeCollision "GrenadeCollision"
#define	C_color_grenadeprediction_circle "grenadeprediction_circle"
#define	C_color_grenadeprediction "grenadeprediction"

#define	C_fakechams "fakechams"

#define	C_fill_color_team "fillboxct"
#define	C_fill_color_enemy "fillboxtt"
#define	C_flTracers "flTracers"
#define	C_esp_Ambient "esp_Ambient"

#define	C_skeleton "skeleton"
#define	C_hitbox "hitbox"


#define	C_Crosshair "Crosshair"
#define	C_Scope "Scope"
#define	C_CrsSpread "CrosshairSpread"
#define	C_TeamSkeleton "TeamSkeleton"
#define	C_EnemySkeleton "EnemySkeleton"
#define	C_TeamSkeletonINVIS "TeamSkeletonINVIS"
#define	C_EnemySkeletonInVIS "EnemySkeletonInVIS"
#define	C_ESP_Color_VCT "Color Visible CT"
#define	C_ESP_Color_VTT "Color Visible T"
#define	C_ESP_Color_CT "Color CT"
#define	C_ESP_Color_TT "Color T"
#define	C_EnemyGlow "EnemyGlow"
#define	C_TeamGlow "TeamGlow"
#define	C_WeaponGlow "WeaponGlow"
#define	C_C4glow "C4glow"
#define	C_EnemyChamsVis "EnemyChamsVis"
#define	C_EnemyChamsNVis "EnemyChamsNVis"
#define	C_TeamChamsVis "TeamChamsVis"
#define	C_TeamChamsNVis "TeamChamsNVis"
#define	C_WeaponDropped "WeaponDropped"
#define	C_HandCham "HandCham"
#define	C_WeaponHandCham "WeaponHandCham"

#define	C_rad_Color_CT "rad_Color_CT"
#define	C_rad_Color_TT "rad_Color_TT"
#define	C_rad_Color_VCT "rad_Color_VCT"
#define	C_rad_Color_VTT "rad_Color_VTT"
#define	C_Light_CT "Light_CT"
#define	C_Light_TT "Light_TT"
#define	C_WorldMode "WorldMode"

#define	C_rad_Alpha "rad_Alpha"

#define	St_Themes "ThemesMenw"



